# Generated by Django 5.0.6 on 2024-05-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Items",
            new_name="Item",
        ),
    ]
