# Generated by Django 5.0.6 on 2024-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_delete_item_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="checkout",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
