# Generated by Django 5.0.6 on 2024-06-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_order_checkout_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="static/placeholder.jpg", upload_to="static/"
            ),
        ),
    ]
