# Generated by Django 5.0.6 on 2024-06-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0006_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="food/placeholder.jpg", upload_to="static/"
            ),
        ),
    ]
